import greenfoot.*;  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)

public class Floor4 extends World {
    public static int counter;
    public static GreenfootSound sound; 
    public static boolean worldBoolean;

    public Floor4() {
        super(1300, 700, 1);
        this.counter = 115;
        this.worldBoolean = true;
        terraForming();
        sound = new GreenfootSound("Undertale OST 005 - Ruins.mp3");
        sound.playLoop();
        prepare();
    }
    protected void terraForming() {
        int tellerWall = 0;
        int tellerVWall = 0;

        addObject(new Link(), 650, 350);
        addObject(new Mr_Bones(), 650, 600);

        setPaintOrder(
                Mr_Bones_FinalForm.class,
                Link.class,
                Mr_Bones.class,
                RollingBomb.class,
                YellowWall.class,
                YellowVerticalWall.class,
                DungeonStairsFloor4.class,
                GreenRupee.class,
                Door.class
        );
    }
    private void prepare() {
        YellowVerticalWall yellowVerticalWall = new YellowVerticalWall();
        addObject(yellowVerticalWall, 648, 295);
        YellowWall yellowWall = new YellowWall();
        addObject(yellowWall, 689, 257);
        YellowWall yellowWall2 = new YellowWall();
        addObject(yellowWall2, 608, 287);
        YellowVerticalWall yellowVerticalWall2 = new YellowVerticalWall();
        addObject(yellowVerticalWall2, 568, 259);
        YellowWall yellowWall3 = new YellowWall();
        addObject(yellowWall3, 690, 321);
        YellowVerticalWall yellowVerticalWall3 = new YellowVerticalWall();
        addObject(yellowVerticalWall3, 730, 353);
        YellowWall yellowWall4 = new YellowWall();
        addObject(yellowWall4, 764, 385);
        YellowVerticalWall yellowVerticalWall4 = new YellowVerticalWall();
        addObject(yellowVerticalWall4, 766, 419);
        YellowVerticalWall yellowVerticalWall5 = new YellowVerticalWall();
        addObject(yellowVerticalWall5, 756, 474);
        YellowVerticalWall yellowVerticalWall6 = new YellowVerticalWall();
        addObject(yellowVerticalWall6, 778, 523);
        YellowWall yellowWall5 = new YellowWall();
        addObject(yellowWall5, 530, 263);
        YellowWall yellowWall6 = new YellowWall();
        addObject(yellowWall6, 470, 253);
        YellowWall yellowWall7 = new YellowWall();
        addObject(yellowWall7, 416, 267);
        YellowWall yellowWall8 = new YellowWall();
        addObject(yellowWall8, 362, 295);
        YellowWall yellowWall9 = new YellowWall();
        addObject(yellowWall9, 306, 325);
        YellowVerticalWall yellowVerticalWall7 = new YellowVerticalWall();
        addObject(yellowVerticalWall7, 291, 371);
        YellowVerticalWall yellowVerticalWall8 = new YellowVerticalWall();
        addObject(yellowVerticalWall8, 292, 429);
        YellowVerticalWall yellowVerticalWall9 = new YellowVerticalWall();
        addObject(yellowVerticalWall9, 294, 483);
        YellowVerticalWall yellowVerticalWall10 = new YellowVerticalWall();
        addObject(yellowVerticalWall10, 296, 525);
        yellowVerticalWall10.setLocation(310, 547);
        YellowVerticalWall yellowVerticalWall11 = new YellowVerticalWall();
        addObject(yellowVerticalWall11, 310, 547);
        YellowVerticalWall yellowVerticalWall12 = new YellowVerticalWall();
        addObject(yellowVerticalWall12, 332, 560);
        YellowVerticalWall yellowVerticalWall13 = new YellowVerticalWall();
        addObject(yellowVerticalWall13, 360, 564);
        YellowVerticalWall yellowVerticalWall14 = new YellowVerticalWall();
        addObject(yellowVerticalWall14, 360, 626);
        YellowVerticalWall yellowVerticalWall15 = new YellowVerticalWall();
        addObject(yellowVerticalWall15, 472, 419);
        YellowWall yellowWall10 = new YellowWall();
        addObject(yellowWall10, 471, 379);
        YellowWall yellowWall11 = new YellowWall();
        addObject(yellowWall11, 471, 455);
        YellowVerticalWall yellowVerticalWall16 = new YellowVerticalWall();
        addObject(yellowVerticalWall16, 648, 234);
        YellowVerticalWall yellowVerticalWall17 = new YellowVerticalWall();
        addObject(yellowVerticalWall17, 648, 173);
        YellowVerticalWall yellowVerticalWall18 = new YellowVerticalWall();
        addObject(yellowVerticalWall18, 648, 111);
        YellowWall yellowWall12 = new YellowWall();
        addObject(yellowWall12, 601, 157);
        YellowWall yellowWall13 = new YellowWall();
        addObject(yellowWall13, 543, 157);
        YellowWall yellowWall14 = new YellowWall();
        addObject(yellowWall14, 492, 156);
        YellowVerticalWall yellowVerticalWall19 = new YellowVerticalWall();
        addObject(yellowVerticalWall19, 461, 171);
        YellowVerticalWall yellowVerticalWall20 = new YellowVerticalWall();
        addObject(yellowVerticalWall20, 522, 112);
        YellowVerticalWall yellowVerticalWall21 = new YellowVerticalWall();
        addObject(yellowVerticalWall21, 521, 3);
        YellowVerticalWall yellowVerticalWall22 = new YellowVerticalWall();
        addObject(yellowVerticalWall22, 648, 61);
        YellowVerticalWall yellowVerticalWall23 = new YellowVerticalWall();
        addObject(yellowVerticalWall23, 347, 248);
        YellowVerticalWall yellowVerticalWall24 = new YellowVerticalWall();
        addObject(yellowVerticalWall24, 347, 186);
        YellowVerticalWall yellowVerticalWall25 = new YellowVerticalWall();
        addObject(yellowVerticalWall25, 552, 393);
        YellowVerticalWall yellowVerticalWall26 = new YellowVerticalWall();
        addObject(yellowVerticalWall26, 393, 393);
        YellowVerticalWall yellowVerticalWall27 = new YellowVerticalWall();
        addObject(yellowVerticalWall27, 801, 575);
        yellowVerticalWall10.setLocation(306, 520);
        YellowVerticalWall yellowVerticalWall28 = new YellowVerticalWall();
        addObject(yellowVerticalWall28, 306, 520);
        YellowWall yellowWall15 = new YellowWall();
        addObject(yellowWall15, 255, 468);
        YellowWall yellowWall16 = new YellowWall();
        addObject(yellowWall16, 199, 468);
        YellowWall yellowWall17 = new YellowWall();
        addObject(yellowWall17, 148, 468);
        YellowWall yellowWall18 = new YellowWall();
        addObject(yellowWall18, 96, 468);
        YellowWall yellowWall19 = new YellowWall();
        addObject(yellowWall19, 28, 404);
        YellowWall yellowWall20 = new YellowWall();
        addObject(yellowWall20, 88, 404);
        YellowWall yellowWall21 = new YellowWall();
        addObject(yellowWall21, 148, 404);
        YellowWall yellowWall22 = new YellowWall();
        addObject(yellowWall22, 207, 404);
        YellowWall yellowWall23 = new YellowWall();
        addObject(yellowWall23, 256, 325);
        YellowVerticalWall yellowVerticalWall29 = new YellowVerticalWall();
        addObject(yellowVerticalWall29, 208, 310);
        YellowVerticalWall yellowVerticalWall30 = new YellowVerticalWall();
        addObject(yellowVerticalWall30, 208, 249);
        YellowWall yellowWall24 = new YellowWall();
        addObject(yellowWall24, 256, 234);
        YellowWall yellowWall25 = new YellowWall();
        addObject(yellowWall25, 162, 234);
        YellowVerticalWall yellowVerticalWall31 = new YellowVerticalWall();
        addObject(yellowVerticalWall31, 271, 188);
        YellowWall yellowWall26 = new YellowWall();
        addObject(yellowWall26, 112, 320);
        YellowVerticalWall yellowVerticalWall32 = new YellowVerticalWall();
        addObject(yellowVerticalWall32, 64, 305);
        YellowVerticalWall yellowVerticalWall33 = new YellowVerticalWall();
        addObject(yellowVerticalWall33, 64, 244);
        YellowVerticalWall yellowVerticalWall34 = new YellowVerticalWall();
        addObject(yellowVerticalWall34, 64, 184);
        YellowVerticalWall yellowVerticalWall35 = new YellowVerticalWall();
        addObject(yellowVerticalWall35, 64, 124);
        YellowVerticalWall yellowVerticalWall36 = new YellowVerticalWall();
        addObject(yellowVerticalWall36, 64, 78);
        YellowWall yellowWall27 = new YellowWall();
        addObject(yellowWall27, 112, 63);
        YellowVerticalWall yellowVerticalWall37 = new YellowVerticalWall();
        addObject(yellowVerticalWall37, 147, 188);
        yellowVerticalWall5.setLocation(755, 485);
        YellowVerticalWall yellowVerticalWall38 = new YellowVerticalWall();
        addObject(yellowVerticalWall38, 147, 78);
        YellowVerticalWall yellowVerticalWall39 = new YellowVerticalWall();
        addObject(yellowVerticalWall39, 211, 133);
        YellowVerticalWall yellowVerticalWall40 = new YellowVerticalWall();
        addObject(yellowVerticalWall40, 271, 79);
        YellowWall yellowWall28 = new YellowWall();
        addObject(yellowWall28, 256, 158);
        YellowWall yellowWall29 = new YellowWall();
        addObject(yellowWall29, 317, 64);
        YellowWall yellowWall30 = new YellowWall();
        addObject(yellowWall30, 378, 64);
        YellowWall yellowWall31 = new YellowWall();
        addObject(yellowWall31, 439, 64);
        YellowWall yellowWall32 = new YellowWall();
        addObject(yellowWall32, 392, 171);
        YellowWall yellowWall33 = new YellowWall();
        addObject(yellowWall33, 24, 540);
        YellowWall yellowWall34 = new YellowWall();
        addObject(yellowWall34, 85, 540);
        YellowWall yellowWall35 = new YellowWall();
        addObject(yellowWall35, 146, 540);
        YellowWall yellowWall36 = new YellowWall();
        addObject(yellowWall36, 208, 540);
        YellowWall yellowWall37 = new YellowWall();
        addObject(yellowWall37, 316, 655);
        YellowWall yellowWall38 = new YellowWall();
        addObject(yellowWall38, 256, 655);
        YellowWall yellowWall39 = new YellowWall();
        addObject(yellowWall39, 197, 655);
        YellowWall yellowWall40 = new YellowWall();
        addObject(yellowWall40, 136, 655);
        YellowWall yellowWall41 = new YellowWall();
        addObject(yellowWall41, 76, 655);
        YellowVerticalWall yellowVerticalWall41 = new YellowVerticalWall();
        addObject(yellowVerticalWall41, 70, 586);
        YellowVerticalWall yellowVerticalWall42 = new YellowVerticalWall();
        addObject(yellowVerticalWall42, 131, 611);
        YellowVerticalWall yellowVerticalWall43 = new YellowVerticalWall();
        addObject(yellowVerticalWall43, 186, 585);
        YellowVerticalWall yellowVerticalWall44 = new YellowVerticalWall();
        addObject(yellowVerticalWall44, 248, 611);
        yellowVerticalWall5.setLocation(759, 459);
        YellowVerticalWall yellowVerticalWall45 = new YellowVerticalWall();
        addObject(yellowVerticalWall45, 759, 462);
        YellowWall yellowWall42 = new YellowWall();
        addObject(yellowWall42, 816, 620);
        YellowWall yellowWall43 = new YellowWall();
        addObject(yellowWall43, 878, 620);
        YellowWall yellowWall44 = new YellowWall();
        addObject(yellowWall44, 922, 603);
        YellowWall yellowWall45 = new YellowWall();
        addObject(yellowWall45, 977, 588);
        YellowWall yellowWall46 = new YellowWall();
        addObject(yellowWall46, 1032, 568);
        YellowWall yellowWall47 = new YellowWall();
        addObject(yellowWall47, 1092, 544);
        YellowWall yellowWall48 = new YellowWall();
        addObject(yellowWall48, 1152, 521);
        YellowWall yellowWall49 = new YellowWall();
        addObject(yellowWall49, 952, 693);
        YellowWall yellowWall50 = new YellowWall();
        addObject(yellowWall50, 1012, 678);
        YellowWall yellowWall51 = new YellowWall();
        addObject(yellowWall51, 892, 699);
        YellowWall yellowWall52 = new YellowWall();
        addObject(yellowWall52, 1072, 658);
        YellowWall yellowWall53 = new YellowWall();
        addObject(yellowWall53, 1127, 637);
        YellowWall yellowWall54 = new YellowWall();
        addObject(yellowWall54, 1180, 619);
        YellowWall yellowWall55 = new YellowWall();
        addObject(yellowWall55, 1218, 592);
        YellowWall yellowWall56 = new YellowWall();
        addObject(yellowWall56, 1240, 568);
        BlueRupee blueRupee = new BlueRupee();
        addObject(blueRupee, 1123, 680);
        GreenRupee greenRupee = new GreenRupee();
        addObject(greenRupee, 1146, 678);
        GreenRupee greenRupee2 = new GreenRupee();
        addObject(greenRupee2, 1172, 670);
        GreenRupee greenRupee3 = new GreenRupee();
        addObject(greenRupee3, 1196, 659);
        BlueRupee blueRupee2 = new BlueRupee();
        addObject(blueRupee2, 247, 286);
        BlueRupee blueRupee3 = new BlueRupee();
        addObject(blueRupee3, 234, 197);
        BlueRupee blueRupee4 = new BlueRupee();
        addObject(blueRupee4, 607, 245);
        GreenRupee greenRupee4 = new GreenRupee();
        addObject(greenRupee4, 380, 231);
        GreenRupee greenRupee5 = new GreenRupee();
        addObject(greenRupee5, 104, 102);
        GreenRupee greenRupee6 = new GreenRupee();
        addObject(greenRupee6, 30, 503);
        BlueRupee blueRupee5 = new BlueRupee();
        addObject(blueRupee5, 324, 616);
        GreenRupee greenRupee7 = new GreenRupee();
        addObject(greenRupee7, 284, 614);
        GreenRupee greenRupee8 = new GreenRupee();
        addObject(greenRupee8, 942, 651);
        BlueRupee blueRupee6 = new BlueRupee();
        addObject(blueRupee6, 500, 415);
        BlueRupee blueRupee7 = new BlueRupee();
        addObject(blueRupee7, 443, 415);
        GreenRupee greenRupee9 = new GreenRupee();
        addObject(greenRupee9, 360, 677);
        YellowVerticalWall yellowVerticalWall46 = new YellowVerticalWall();
        addObject(yellowVerticalWall46, 1255, 528);
        YellowVerticalWall yellowVerticalWall47 = new YellowVerticalWall();
        addObject(yellowVerticalWall47, 1256, 466);
        YellowVerticalWall yellowVerticalWall48 = new YellowVerticalWall();
        addObject(yellowVerticalWall48, 1256, 406);
        YellowVerticalWall yellowVerticalWall49 = new YellowVerticalWall();
        addObject(yellowVerticalWall49, 1167, 479);
        YellowVerticalWall yellowVerticalWall50 = new YellowVerticalWall();
        addObject(yellowVerticalWall50, 1166, 417);
        YellowVerticalWall yellowVerticalWall51 = new YellowVerticalWall();
        addObject(yellowVerticalWall51, 1169, 358);
        YellowWall yellowWall57 = new YellowWall();
        addObject(yellowWall57, 1131, 459);
        YellowWall yellowWall58 = new YellowWall();
        addObject(yellowWall58, 1071, 459);
        YellowWall yellowWall59 = new YellowWall();
        addObject(yellowWall59, 1031, 459);
        YellowWall yellowWall60 = new YellowWall();
        addObject(yellowWall60, 996, 459);
        YellowWall yellowWall61 = new YellowWall();
        addObject(yellowWall61, 954, 459);
        YellowWall yellowWall62 = new YellowWall();
        addObject(yellowWall62, 915, 459);
        YellowWall yellowWall63 = new YellowWall();
        addObject(yellowWall63, 871, 459);
        YellowVerticalWall yellowVerticalWall52 = new YellowVerticalWall();
        addObject(yellowVerticalWall52, 856, 371);
        YellowVerticalWall yellowVerticalWall53 = new YellowVerticalWall();
        addObject(yellowVerticalWall53, 856, 311);
        YellowVerticalWall yellowVerticalWall54 = new YellowVerticalWall();
        addObject(yellowVerticalWall54, 779, 339);
        YellowVerticalWall yellowVerticalWall55 = new YellowVerticalWall();
        addObject(yellowVerticalWall55, 723, 224);
        BlueRupee blueRupee8 = new BlueRupee();
        addObject(blueRupee8, 684, 215);
        YellowVerticalWall yellowVerticalWall56 = new YellowVerticalWall();
        addObject(yellowVerticalWall56, 723, 164);
        YellowVerticalWall yellowVerticalWall57 = new YellowVerticalWall();
        addObject(yellowVerticalWall57, 856, 251);
        YellowVerticalWall yellowVerticalWall58 = new YellowVerticalWall();
        addObject(yellowVerticalWall58, 856, 191);
        YellowVerticalWall yellowVerticalWall59 = new YellowVerticalWall();
        addObject(yellowVerticalWall59, 856, 421);
        GhostWall ghostWall = new GhostWall();
        addObject(ghostWall, 901, 389);
        GhostWall ghostWall2 = new GhostWall();
        addObject(ghostWall2, 963, 389);
        GhostWall ghostWall3 = new GhostWall();
        addObject(ghostWall3, 1024, 389);
        GhostWall ghostWall4 = new GhostWall();
        addObject(ghostWall4, 1084, 389);
        BlueRupee blueRupee9 = new BlueRupee();
        addObject(blueRupee9, 889, 425);
        GhostVerticalWall ghostVerticalWall = new GhostVerticalWall();
        addObject(ghostVerticalWall, 1009, 350);
        GhostVerticalWall ghostVerticalWall2 = new GhostVerticalWall();
        addObject(ghostVerticalWall2, 1099, 343);
        YellowVerticalWall yellowVerticalWall60 = new YellowVerticalWall();
        addObject(yellowVerticalWall60, 1170, 299);
        YellowVerticalWall yellowVerticalWall61 = new YellowVerticalWall();
        addObject(yellowVerticalWall61, 1170, 237);
        YellowVerticalWall yellowVerticalWall62 = new YellowVerticalWall();
        addObject(yellowVerticalWall62, 1170, 176);
        GreenRupee greenRupee10 = new GreenRupee();
        addObject(greenRupee10, 1008, 306);
        GhostVerticalWall ghostVerticalWall3 = new GhostVerticalWall();
        addObject(ghostVerticalWall3, 1009, 261);
        GhostVerticalWall ghostVerticalWall4 = new GhostVerticalWall();
        addObject(ghostVerticalWall4, 1099, 283);
        YellowVerticalWall yellowVerticalWall63 = new YellowVerticalWall();
        addObject(yellowVerticalWall63, 1170, 115);
        GhostVerticalWall ghostVerticalWall19 = new GhostVerticalWall();
        addObject(ghostVerticalWall19, 1099, 222);
        GhostWall ghostWall18 = new GhostWall();
        addObject(ghostWall18, 994, 213);
        BlueRupee blueRupee10 = new BlueRupee();
        addObject(blueRupee10, 916, 425);
        BlueRupee blueRupee11 = new BlueRupee();
        addObject(blueRupee11, 944, 426);
        BlueRupee blueRupee12 = new BlueRupee();
        addObject(blueRupee12, 974, 425);
        GhostWall ghostWall5 = new GhostWall();
        addObject(ghostWall5, 1126, 100);
        GhostWall ghostWall6 = new GhostWall();
        addObject(ghostWall6, 1068, 100);
        GhostWall ghostWall7 = new GhostWall();
        addObject(ghostWall7, 1009, 100);
        YellowVerticalWall yellowVerticalWall64 = new YellowVerticalWall();
        addObject(yellowVerticalWall64, 856, 130);
        GhostWall ghostWall8 = new GhostWall();
        addObject(ghostWall8, 880, 100);
        GhostWall ghostWall9 = new GhostWall();
        addObject(ghostWall9, 1084, 175);
        GhostWall ghostWall10 = new GhostWall();
        addObject(ghostWall10, 1034, 156);
        GhostVerticalWall ghostVerticalWall5 = new GhostVerticalWall();
        addObject(ghostVerticalWall5, 963, 115);
        GhostVerticalWall ghostVerticalWall6 = new GhostVerticalWall();
        addObject(ghostVerticalWall6, 963, 176);
        GhostWall ghostWall11 = new GhostWall();
        addObject(ghostWall11, 903, 269);
        GhostVerticalWall ghostVerticalWall7 = new GhostVerticalWall();
        addObject(ghostVerticalWall7, 934, 300);
        BlueRupee blueRupee13 = new BlueRupee();
        addObject(blueRupee13, 896, 318);
        YellowWall yellowWall64 = new YellowWall();
        addObject(yellowWall64, 813, 115);
        YellowWall yellowWall65 = new YellowWall();
        addObject(yellowWall65, 696, 81);
        BlueRupee blueRupee14 = new BlueRupee();
        addObject(blueRupee14, 1096, 500);
        BlueRupee blueRupee15 = new BlueRupee();
        addObject(blueRupee15, 1009, 498);
        BlueRupee blueRupee16 = new BlueRupee();
        addObject(blueRupee16, 968, 553);
        BlueRupee blueRupee17 = new BlueRupee();
        addObject(blueRupee17, 729, 291);
        GreenRupee greenRupee11 = new GreenRupee();
        addObject(greenRupee11, 302, 97);
        GreenRupee greenRupee12 = new GreenRupee();
        addObject(greenRupee12, 470, 343);
        GreenRupee greenRupee13 = new GreenRupee();
        addObject(greenRupee13, 1284, 395);
        GreenRupee greenRupee14 = new GreenRupee();
        addObject(greenRupee14, 991, 135);
        GreenRupee greenRupee15 = new GreenRupee();
        addObject(greenRupee15, 1137, 136);
        GreenRupee greenRupee16 = new GreenRupee();
        addObject(greenRupee16, 936, 349);
        GreenRupee greenRupee17 = new GreenRupee();
        addObject(greenRupee17, 720, 115);
        GhostWall ghostWall13 = new GhostWall();
        addObject(ghostWall13, 1216, 299);
        GhostWall ghostWall14 = new GhostWall();
        addObject(ghostWall14, 1271, 227);
        GhostWall ghostWall15 = new GhostWall();
        addObject(ghostWall15, 1213, 164);
        GreenRupee greenRupee18 = new GreenRupee();
        addObject(greenRupee18, 1211, 258);
        GreenRupee greenRupee19 = new GreenRupee();
        addObject(greenRupee19, 1270, 188);
        GreenRupee greenRupee20 = new GreenRupee();
        addObject(greenRupee20, 1211, 122);
        BlueRupee blueRupee18 = new BlueRupee();
        addObject(blueRupee18, 609, 118);
        BlueRupee blueRupee19 = new BlueRupee();
        addObject(blueRupee19, 20, 184);
        StrafingBomb strafingBomb = new StrafingBomb();
        addObject(strafingBomb, 582, 18);
        StrafingBomb strafingBomb2 = new StrafingBomb();
        addObject(strafingBomb2, 18, 18);
        StrafingBomb strafingBomb3 = new StrafingBomb();
        addObject(strafingBomb3, 336, 491);
        StrafingBomb strafingBomb4 = new StrafingBomb();
        addObject(strafingBomb4, 822, 493);
        StrafingBomb strafingBomb5 = new StrafingBomb();
        addObject(strafingBomb5, 84, 363);
        DungeonStairsFloor5 dungeonStairsFloor5 = new DungeonStairsFloor5();
        addObject(dungeonStairsFloor5,650,667);
    }
}