import greenfoot.*;

public class Floor6 extends World {
    public static int counter;
    public static GreenfootSound sound; 
    public static boolean worldBoolean;
    public Floor6() {    
        super(1300,700,1); 
        this.counter = 120;
        this.worldBoolean = true;
        terraForming();
        sound = new GreenfootSound("Undertale OST 072 - Song That Might Play When You Fight Sans.mp3");
        sound.playLoop();
        prepare();
    }

    protected void terraForming() {
        int tellerWall = 0;
        int tellerVWall = 0;

        addObject(new Link(), 650, 350);
        addObject(new Mr_Bones(), 650, 600);

        setPaintOrder(
            Mr_Bones_FinalForm.class,
            Link.class,
            Mr_Bones.class,
            RollingBomb.class,
            BlackWall.class,
            BlackVerticalWall.class,
            DungeonStairsFloor4.class,
            GreenRupee.class,
            Door.class
        );
    }

    /**
     * Prepare the world for the start of the program.
     * That is: create the initial objects and add them to the world.
     */
    private void prepare() {
        BlackWall blackWall = new BlackWall();
        addObject(blackWall,658,287);

        BlackVerticalWall blackVerticalWall = new BlackVerticalWall();
        addObject(blackVerticalWall,697,253);
        BlackVerticalWall blackVerticalWall2 = new BlackVerticalWall();
        addObject(blackVerticalWall2,697,197);
        BlackVerticalWall blackVerticalWall3 = new BlackVerticalWall();
        addObject(blackVerticalWall3,697,137);

        BlackWall blackWall2 = new BlackWall();
        addObject(blackWall2,741,192);
        BlackWall blackWall3 = new BlackWall();
        addObject(blackWall3,802,192);
        BlackWall blackWall4 = new BlackWall();
        addObject(blackWall4,863,192);
        BlackWall blackWall5 = new BlackWall();
        addObject(blackWall5,924,192);
        BlackWall blackWall6 = new BlackWall();
        addObject(blackWall6,600,287);
        BlackWall blackWall7 = new BlackWall();
        addObject(blackWall7,540,287);
        BlackWall blackWall8 = new BlackWall();
        addObject(blackWall8,498,259);
        BlackWall blackWall9 = new BlackWall();
        addObject(blackWall9,448,230);
        BlackWall blackWall10 = new BlackWall();
        addObject(blackWall10,416,204);

        BlackWall blackWall11 = new BlackWall();
        addObject(blackWall11,372,180);
        BlackWall blackWall12 = new BlackWall();
        addObject(blackWall12,325,159);
        BlackWall blackWall13 = new BlackWall();
        addObject(blackWall13,288,144);
        BlackWall blackWall14 = new BlackWall();
        addObject(blackWall14,336,124);
        BlackWall blackWall15 = new BlackWall();
        addObject(blackWall15,378,106);
        BlackWall blackWall16 = new BlackWall();
        addObject(blackWall16,429,87);
        BlackWall blackWall17 = new BlackWall();
        addObject(blackWall17,480,68);
        BlackWall blackWall18 = new BlackWall();
        addObject(blackWall18,525,51);
        BlackWall blackWall19 = new BlackWall();
        addObject(blackWall19,577,37);
        BlackWall blackWall20 = new BlackWall();
        addObject(blackWall20,625,59);
        BlackWall blackWall21 = new BlackWall();
        addObject(blackWall21,682,100);

        BlueRupee blueRupee = new BlueRupee();
        addObject(blueRupee,665,248);
        BlueRupee blueRupee2 = new BlueRupee();
        addObject(blueRupee2,544,250);
        BlueRupee blueRupee3 = new BlueRupee();
        addObject(blueRupee3,466,192);
        BlueRupee blueRupee4 = new BlueRupee();
        addObject(blueRupee4,472,102);
        BlueRupee blueRupee5 = new BlueRupee();
        addObject(blueRupee5,574,74);
        BlueRupee blueRupee6 = new BlueRupee();
        addObject(blueRupee6,666,132);
        BlueRupee blueRupee7 = new BlueRupee();
        addObject(blueRupee7,572,171);

        BlackWall blackWall22 = new BlackWall();
        addObject(blackWall22,969,220);
        BlackWall blackWall23 = new BlackWall();
        addObject(blackWall23,1006,251);
        BlackWall blackWall24 = new BlackWall();
        addObject(blackWall24,917,285);
        BlackWall blackWall25 = new BlackWall();
        addObject(blackWall25,871,312);
        BlackWall blackWall26 = new BlackWall();
        addObject(blackWall26,800,346);
        BlackWall blackWall27 = new BlackWall();
        addObject(blackWall27,839,328);
        BlackWall blackWall28 = new BlackWall();
        addObject(blackWall28,748,366);
        BlackWall blackWall29 = new BlackWall();
        addObject(blackWall29,714,388);
        BlackWall blackWall30 = new BlackWall();
        addObject(blackWall30,714,416);
        BlackWall blackWall31 = new BlackWall();
        addObject(blackWall31,652,416);
        BlackWall blackWall32 = new BlackWall();
        addObject(blackWall32,688,59);
        BlackWall blackWall33 = new BlackWall();
        addObject(blackWall33,744,35);

        BlackVerticalWall blackVerticalWall4 = new BlackVerticalWall();
        addObject(blackVerticalWall4,1045,212);
        BlackVerticalWall blackVerticalWall5 = new BlackVerticalWall();
        addObject(blackVerticalWall5,1065,168);
        BlackVerticalWall blackVerticalWall6 = new BlackVerticalWall();
        addObject(blackVerticalWall6,1088,132);
        BlackVerticalWall blackVerticalWall7 = new BlackVerticalWall();
        addObject(blackVerticalWall7,1110,91);
        BlackVerticalWall blackVerticalWall8 = new BlackVerticalWall();
        addObject(blackVerticalWall8,1141,91);
        BlackVerticalWall blackVerticalWall9 = new BlackVerticalWall();
        addObject(blackVerticalWall9,1172,91);

        BlackVerticalWall blackVerticalWall10 = new BlackVerticalWall();
        addObject(blackVerticalWall10,1021,296);
        BlackWall blackWall34 = new BlackWall();
        addObject(blackWall34,1206,122);
        BlackWall blackWall35 = new BlackWall();
        addObject(blackWall35,594,426);
        BlackWall blackWall36 = new BlackWall();
        addObject(blackWall36,545,413);
        BlackWall blackWall37 = new BlackWall();
        addObject(blackWall37,502,401);
        BlackWall blackWall38 = new BlackWall();
        addObject(blackWall38,456,378);
        BlackWall blackWall39 = new BlackWall();
        addObject(blackWall39,408,364);
        BlackWall blackWall40 = new BlackWall();
        addObject(blackWall40,364,347);
        BlackWall blackWall41 = new BlackWall();
        addObject(blackWall41,320,333);
        BlackWall blackWall42 = new BlackWall();
        addObject(blackWall42,273,311);
        BlackWall blackWall43 = new BlackWall();
        addObject(blackWall43,232,300);
        BlackWall blackWall44 = new BlackWall();
        addObject(blackWall44,199,279);
        BlackWall blackWall45 = new BlackWall();
        addObject(blackWall45,186,258);
        BlackWall blackWall46 = new BlackWall();
        addObject(blackWall46,158,231);
        BlackWall blackWall47 = new BlackWall();
        addObject(blackWall47,158,212);
        BlackWall blackWall48 = new BlackWall();
        addObject(blackWall48,160,188);
        BlackWall blackWall49 = new BlackWall();
        addObject(blackWall49,163,161);
        BlackWall blackWall50 = new BlackWall();
        addObject(blackWall50,172,142);
        BlackWall blackWall51 = new BlackWall();
        addObject(blackWall51,193,115);
        BlackWall blackWall52 = new BlackWall();
        addObject(blackWall52,239,88);
        BlackWall blackWall53 = new BlackWall();
        addObject(blackWall53,286,78);
        BlackWall blackWall54 = new BlackWall();
        addObject(blackWall54,348,64);
        BlackWall blackWall55 = new BlackWall();
        addObject(blackWall55,577,6);
        BlackWall blackWall56 = new BlackWall();
        addObject(blackWall56,72,283);
        BlackWall blackWall57 = new BlackWall();
        addObject(blackWall57,88,311);
        BlackWall blackWall58 = new BlackWall();
        addObject(blackWall58,99,333);
        BlackWall blackWall59 = new BlackWall();
        addObject(blackWall59,112,357);
        BlackWall blackWall60 = new BlackWall();
        addObject(blackWall60,120,376);
        BlackWall blackWall61 = new BlackWall();
        addObject(blackWall61,128,395);
        BlackWall blackWall62 = new BlackWall();
        addObject(blackWall62,136,413);
        BlackWall blackWall63 = new BlackWall();
        addObject(blackWall63,147,439);
        BlackWall blackWall64 = new BlackWall();
        addObject(blackWall64,162,462);
        BlackWall blackWall65 = new BlackWall();
        addObject(blackWall65,174,484);
        BlackWall blackWall66 = new BlackWall();
        addObject(blackWall66,190,509);
        BlackWall blackWall67 = new BlackWall();
        addObject(blackWall67,197,523);
        BlackWall blackWall68 = new BlackWall();
        addObject(blackWall68,204,540);
        BlackWall blackWall69 = new BlackWall();
        addObject(blackWall69,217,556);
        BlackWall blackWall70 = new BlackWall();
        addObject(blackWall70,227,580);
        BlackWall blackWall71 = new BlackWall();
        addObject(blackWall71,236,604);
        BlackWall blackWall72 = new BlackWall();
        addObject(blackWall72,246,626);
        BlackWall blackWall73 = new BlackWall();
        addObject(blackWall73,278,677);
        BlackWall blackWall74 = new BlackWall();
        addObject(blackWall74,280,647);
        BlackWall blackWall75 = new BlackWall();
        addObject(blackWall75,322,689);
        StrafingBomb strafingBomb = new StrafingBomb();
        addObject(strafingBomb,796,103);
        StrafingBomb strafingBomb2 = new StrafingBomb();
        addObject(strafingBomb2,1093,283);
        StrafingBomb strafingBomb3 = new StrafingBomb();
        addObject(strafingBomb3,275,220);
        StrafingBomb strafingBomb4 = new StrafingBomb();
        addObject(strafingBomb4,224,431);
        StrafingBomb strafingBomb5 = new StrafingBomb();
        addObject(strafingBomb5,57,568);
        StrafingBomb strafingBomb6 = new StrafingBomb();
        addObject(strafingBomb6,48,526);
        StrafingBomb strafingBomb7 = new StrafingBomb();
        addObject(strafingBomb7,73,619);
        StrafingBomb strafingBomb8 = new StrafingBomb();
        addObject(strafingBomb8,41,147);
        StrafingBomb strafingBomb9 = new StrafingBomb();
        addObject(strafingBomb9,67,35);
        StrafingBomb strafingBomb10 = new StrafingBomb();
        addObject(strafingBomb10,864,144);
        StrafingBomb strafingBomb11 = new StrafingBomb();
        addObject(strafingBomb11,834,222);
        BlackVerticalWall blackVerticalWall11 = new BlackVerticalWall();
        addObject(blackVerticalWall11,729,463);
        BlackVerticalWall blackVerticalWall12 = new BlackVerticalWall();
        addObject(blackVerticalWall12,729,521);
        BlackVerticalWall blackVerticalWall13 = new BlackVerticalWall();
        addObject(blackVerticalWall13,729,572);
        BlackVerticalWall blackVerticalWall14 = new BlackVerticalWall();
        addObject(blackVerticalWall14,729,629);
        BlackWall blackWall76 = new BlackWall();
        addObject(blackWall76,684,501);
        BlackWall blackWall77 = new BlackWall();
        addObject(blackWall77,624,501);
        BlackWall blackWall78 = new BlackWall();
        addObject(blackWall78,564,501);
        BlackWall blackWall79 = new BlackWall();
        addObject(blackWall79,504,501);
        BlackWall blackWall80 = new BlackWall();
        addObject(blackWall80,444,501);
        BlackWall blackWall81 = new BlackWall();
        addObject(blackWall81,390,501);
        BlueRupee blueRupee8 = new BlueRupee();
        addObject(blueRupee8,689,461);
        BlackVerticalWall blackVerticalWall15 = new BlackVerticalWall();
        addObject(blackVerticalWall15,550,546);
        BlackVerticalWall blackVerticalWall16 = new BlackVerticalWall();
        addObject(blackVerticalWall16,550,604);
        BlackVerticalWall blackVerticalWall17 = new BlackVerticalWall();
        addObject(blackVerticalWall17,550,624);
        RollingBomb rollingBomb = new RollingBomb();
        addObject(rollingBomb,1017,425);
        RollingBomb rollingBomb2 = new RollingBomb();
        addObject(rollingBomb2,1002,546);
        RollingBomb rollingBomb3 = new RollingBomb();
        addObject(rollingBomb3,1114,531);
        RollingBomb rollingBomb4 = new RollingBomb();
        addObject(rollingBomb4,1184,495);
        RollingBomb rollingBomb5 = new RollingBomb();
        addObject(rollingBomb5,1110,410);
        RollingBomb rollingBomb6 = new RollingBomb();
        addObject(rollingBomb6,1190,398);
        RollingBomb rollingBomb7 = new RollingBomb();
        addObject(rollingBomb7,1084,499);
        RollingBomb rollingBomb8 = new RollingBomb();
        addObject(rollingBomb8,1148,653);
        RollingBomb rollingBomb9 = new RollingBomb();
        addObject(rollingBomb9,1188,555);
        RollingBomb rollingBomb10 = new RollingBomb();
        addObject(rollingBomb10,861,576);
        RollingBomb rollingBomb11 = new RollingBomb();
        addObject(rollingBomb11,887,599);
        RollingBomb rollingBomb12 = new RollingBomb();
        addObject(rollingBomb12,1043,655);
        RollingBomb rollingBomb13 = new RollingBomb();
        addObject(rollingBomb13,904,424);
        RollingBomb rollingBomb14 = new RollingBomb();
        addObject(rollingBomb14,862,446);
        RollingBomb rollingBomb15 = new RollingBomb();
        addObject(rollingBomb15,856,455);
        RollingBomb rollingBomb16 = new RollingBomb();
        addObject(rollingBomb16,874,569);
        RollingBomb rollingBomb17 = new RollingBomb();
        addObject(rollingBomb17,929,441);
        RollingBomb rollingBomb18 = new RollingBomb();
        addObject(rollingBomb18,912,409);
        RollingBomb rollingBomb19 = new RollingBomb();
        addObject(rollingBomb19,937,557);
        RollingBomb rollingBomb20 = new RollingBomb();
        addObject(rollingBomb20,1101,595);
        RollingBomb rollingBomb21 = new RollingBomb();
        addObject(rollingBomb21,989,459);
        RollingBomb rollingBomb22 = new RollingBomb();
        addObject(rollingBomb22,839,523);
        RollingBomb rollingBomb23 = new RollingBomb();
        addObject(rollingBomb23,793,434);
        RollingBomb rollingBomb24 = new RollingBomb();
        addObject(rollingBomb24,977,375);
        RollingBomb rollingBomb25 = new RollingBomb();
        addObject(rollingBomb25,1078,370);
        RollingBomb rollingBomb26 = new RollingBomb();
        addObject(rollingBomb26,1133,475);
        RollingBomb rollingBomb27 = new RollingBomb();
        addObject(rollingBomb27,1233,499);
        RollingBomb rollingBomb28 = new RollingBomb();
        addObject(rollingBomb28,1223,610);
        RollingBomb rollingBomb29 = new RollingBomb();
        addObject(rollingBomb29,1152,600);
        StrafingBomb strafingBomb12 = new StrafingBomb();
        addObject(strafingBomb12,384,580);
        StrafingBomb strafingBomb13 = new StrafingBomb();
        addObject(strafingBomb13,390,636);
        StrafingBomb strafingBomb14 = new StrafingBomb();
        addObject(strafingBomb14,180,669);
        StrafingBomb strafingBomb15 = new StrafingBomb();
        addObject(strafingBomb15,633,546);
        StrafingBomb strafingBomb16 = new StrafingBomb();
        addObject(strafingBomb16,636,601);
        StrafingBomb strafingBomb17 = new StrafingBomb();
        addObject(strafingBomb17,439,140);
        StrafingBomb strafingBomb18 = new StrafingBomb();
        addObject(strafingBomb18,503,192);
        StrafingBomb strafingBomb19 = new StrafingBomb();
        addObject(strafingBomb19,511,112);
        BlueRupee blueRupee9 = new BlueRupee();
        addObject(blueRupee9,1282,680);
        BlueRupee blueRupee10 = new BlueRupee();
        addObject(blueRupee10,1251,680);
        BlueRupee blueRupee11 = new BlueRupee();
        addObject(blueRupee11,1282,636);
        BlueRupee blueRupee12 = new BlueRupee();
        addObject(blueRupee12,628,22);
        BlueRupee blueRupee13 = new BlueRupee();
        addObject(blueRupee13,532,16);
        BlueRupee blueRupee14 = new BlueRupee();
        addObject(blueRupee14,21,680);
        BlueRupee blueRupee15 = new BlueRupee();
        addObject(blueRupee15,56,682);
        BlueRupee blueRupee16 = new BlueRupee();
        addObject(blueRupee16,21,638);
        BlueRupee blueRupee17 = new BlueRupee();
        addObject(blueRupee17,652,460);
        BlueRupee blueRupee18 = new BlueRupee();
        addObject(blueRupee18,584,541);
        BlueRupee blueRupee19 = new BlueRupee();
        addObject(blueRupee19,697,536);
        BlueRupee blueRupee20 = new BlueRupee();
        addObject(blueRupee20,512,540);
        BlueRupee blueRupee21 = new BlueRupee();
        addObject(blueRupee21,921,236);
        BlueRupee blueRupee22 = new BlueRupee();
        addObject(blueRupee22,1280,347);
        BlueRupee blueRupee23 = new BlueRupee();
        addObject(blueRupee23,1214,85);
        BlueRupee blueRupee24 = new BlueRupee();
        addObject(blueRupee24,1012,207);
        DungeonStairsFloor7 dungeonStairsFloor7 = new DungeonStairsFloor7();
        addObject(dungeonStairsFloor7,636,667);
    }
}
